const schemes = [
  {id:"ayushman-bharat",name:"Ayushman Bharat PM-JAY",category:"health",icon:"✚",categoryLabel:"Health",summary:"Health cover for eligible families to access hospital care.",benefit:"Hospital care cover",popular:1,who:"Eligible families identified through government criteria. Eligibility can vary by state and is checked through the official portal.",details:"The scheme provides cashless access to covered secondary and tertiary hospital care at participating hospitals, subject to current programme rules and package limits.",url:"https://pmjay.gov.in/"},
  {id:"pm-kisan",name:"PM-KISAN",category:"farmers",icon:"⌁",categoryLabel:"For farmers",summary:"Income support for eligible landholding farmer families.",benefit:"Direct income support",popular:2,who:"Eligible landholding farmer families, subject to exclusions and verification under current guidelines.",details:"Benefits are paid in instalments to eligible beneficiaries. Aadhaar, land records, and e-KYC requirements may apply. Confirm your status and current requirements on the official portal.",url:"https://pmkisan.gov.in/"},
  {id:"pmay-urban",name:"PMAY-Urban 2.0",category:"housing",icon:"⌂",categoryLabel:"Housing",summary:"Support to help eligible urban families access a pucca home.",benefit:"Housing assistance",popular:3,who:"Eligible urban households that do not own a pucca house anywhere in India, subject to income and other scheme criteria.",details:"PMAY-Urban 2.0 includes different verticals for eligible beneficiaries. Application routes and assistance depend on the selected vertical and current official guidelines.",url:"https://pmay-urban.gov.in/"},
  {id:"sukanya-samriddhi",name:"Sukanya Samriddhi Account",category:"women",icon:"✿",categoryLabel:"Women & families",summary:"A savings account designed for the future of a girl child.",benefit:"Long-term savings",popular:4,who:"A guardian can open an account for a girl child who meets the age requirements. Deposit limits and account rules apply.",details:"This small savings scheme is available through participating banks and post offices. Interest rates and tax treatment are set by current government rules; check official sources before opening.",url:"https://www.indiapost.gov.in/"},
  {id:"pm-ujjwala",name:"Pradhan Mantri Ujjwala Yojana",category:"women",icon:"◉",categoryLabel:"Women & families",summary:"LPG connections for eligible households that need clean cooking fuel.",benefit:"Clean cooking access",popular:5,who:"Adult women from eligible low-income households without an LPG connection, subject to the scheme's current eligibility rules.",details:"Applications are handled through participating LPG distributors and the official portal. Required documents and benefits should be confirmed with the distributor.",url:"https://www.pmuy.gov.in/"},
  {id:"pm-mudra",name:"Pradhan Mantri MUDRA Yojana",category:"business",icon:"↗",categoryLabel:"Business",summary:"Loans through lenders for eligible small business activities.",benefit:"Small business finance",popular:6,who:"Individuals and micro enterprises seeking finance for eligible income-generating activities. Lenders assess each application.",details:"MUDRA supports loans through member lending institutions. Loan terms, eligibility, and approval are determined by the lender; the scheme does not guarantee loan approval.",url:"https://www.mudra.org.in/"},
  {id:"pm-vishwakarma",name:"PM Vishwakarma",category:"business",icon:"✳",categoryLabel:"Business",summary:"Training, tools, and credit support for eligible traditional artisans.",benefit:"Skills & credit support",popular:7,who:"Artisans and craftspeople working in one of the notified traditional trades, subject to enrolment and verification requirements.",details:"The programme can include recognition, skill training, toolkit incentives, and concessional credit, subject to current guidelines and verification.",url:"https://pmvishwakarma.gov.in/"},
  {id:"stand-up-india",name:"Stand-Up India",category:"business",icon:"↑",categoryLabel:"Business",summary:"Bank loans to support eligible women and SC/ST entrepreneurs.",benefit:"Enterprise loans",popular:8,who:"Eligible women or SC/ST entrepreneurs seeking to establish a greenfield enterprise, subject to lender and scheme criteria.",details:"Loans are provided through banks for eligible greenfield ventures. Loan size, margin, and repayment terms are governed by the current scheme and lender assessment.",url:"https://www.standupmitra.in/"},
  {id:"pm-kisan-maandhan",name:"PM-Kisan Maandhan Yojana",category:"farmers",icon:"◷",categoryLabel:"For farmers",summary:"A contributory pension scheme for eligible small and marginal farmers.",benefit:"Pension planning",popular:9,who:"Small and marginal farmers within the scheme's age and landholding limits. Contributions and exclusions apply.",details:"Eligible subscribers contribute monthly amounts based on age at entry. The pension and other conditions are governed by the current official guidelines.",url:"https://maandhan.in/"},
  {id:"pmay-gramin",name:"PMAY-Gramin",category:"housing",icon:"⌂",categoryLabel:"Housing",summary:"Rural housing assistance for eligible households.",benefit:"Rural housing support",popular:10,who:"Rural households identified through the official process and meeting current eligibility and verification criteria.",details:"Assistance is linked to approved beneficiaries and local implementation. Check your status with your Gram Panchayat or the official portal.",url:"https://pmayg.nic.in/"},
  {id:"pm-surya-ghar",name:"PM Surya Ghar: Muft Bijli Yojana",category:"housing",icon:"☼",categoryLabel:"Housing",summary:"Support for eligible households to install rooftop solar systems.",benefit:"Rooftop solar subsidy",popular:11,who:"Residential electricity consumers, subject to technical requirements, vendor participation, and current scheme guidelines.",details:"Applications and subsidy processing are handled through the national portal. Check current eligibility, approved vendors, and installation requirements before proceeding.",url:"https://pmsuryaghar.gov.in/"},
  {id:"pm-fasal-bima",name:"Pradhan Mantri Fasal Bima Yojana",category:"farmers",icon:"❋",categoryLabel:"For farmers",summary:"Crop insurance support for farmers against specified crop losses.",benefit:"Crop risk cover",popular:12,who:"Farmers growing notified crops in notified areas during an active season, subject to enrolment timelines and scheme rules.",details:"Coverage and premium depend on crop, location, season, and current notifications. Apply within the season's window and confirm details with your insurer or local agriculture office.",url:"https://pmfby.gov.in/"}
];

const grid=document.querySelector("#scheme-grid");
const search=document.querySelector("#search");
const empty=document.querySelector("#empty-state");
const clearButton=document.querySelector("#clear-filters");
const dialog=document.querySelector("#detail-dialog");
const categoryNames={all:"All schemes",health:"Health",farmers:"For farmers",women:"Women & families",housing:"Housing",business:"Business"};
let activeCategory="all";
let saved=new Set(JSON.parse(localStorage.getItem("schemesaathi-saved")||"[]"));

function render(){
  const term=search.value.trim().toLowerCase();
  const sort=document.querySelector("#sort").value;
  let shown=schemes.filter(s=>(activeCategory==="all"||s.category===activeCategory)&&(!term||[s.name,s.summary,s.categoryLabel,s.benefit].join(" ").toLowerCase().includes(term)));
  if(sort==="az") shown.sort((a,b)=>a.name.localeCompare(b.name)); else shown.sort((a,b)=>a.popular-b.popular);
  document.querySelector("#all-count").textContent=schemes.length;
  document.querySelector("#results-label").textContent=term?shown.length+" results for “"+search.value.trim()+"”":activeCategory==="all"?"Popular schemes":categoryNames[activeCategory];
  clearButton.hidden=!(term||activeCategory!=="all");
  empty.hidden=shown.length>0;
  grid.hidden=shown.length===0;
  grid.innerHTML=shown.map(s=>'<article class="scheme-card"><div class="card-top"><span class="scheme-icon" aria-hidden="true">'+s.icon+'</span><span class="category-label">'+s.categoryLabel+'</span><button class="save-button '+(saved.has(s.id)?"saved":"")+'" data-save="'+s.id+'" aria-label="'+(saved.has(s.id)?"Remove saved scheme":"Save scheme")+'" aria-pressed="'+saved.has(s.id)+'">'+(saved.has(s.id)?"♥":"♡")+'</button></div><h3>'+s.name+'</h3><p>'+s.summary+'</p><div class="card-bottom"><span class="benefit">'+s.benefit+'</span><button class="learn-button" data-detail="'+s.id+'">Details <span>↗</span></button></div></article>').join("");
  document.querySelector("#saved-count").textContent=saved.size;
}
function clearFilters(){activeCategory="all";search.value="";document.querySelectorAll(".filter-chip").forEach(b=>b.classList.toggle("active",b.dataset.category==="all"));render()}
function openDetails(id){
  const s=schemes.find(item=>item.id===id);if(!s)return;
  document.querySelector("#dialog-content").innerHTML='<span class="dialog-category">'+s.categoryLabel+'</span><h2 id="dialog-title">'+s.name+'</h2><p class="dialog-summary">'+s.summary+'</p><div class="dialog-section"><h3>Who may be eligible</h3><p>'+s.who+'</p></div><div class="dialog-section"><h3>What to know</h3><p>'+s.details+'</p></div><div class="dialog-actions"><a class="button button-dark" href="'+s.url+'" target="_blank" rel="noopener noreferrer">Visit official website <span aria-hidden="true">↗</span></a><button class="learn-button" data-save="'+s.id+'">'+(saved.has(s.id)?"♥ Saved":"♡ Save scheme")+'</button></div><p class="disclaimer">This is a general summary, not an eligibility decision. Confirm current rules with the official scheme source.</p>';
  dialog.showModal();
}
document.querySelector(".filters").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;activeCategory=b.dataset.category;document.querySelectorAll(".filter-chip").forEach(x=>x.classList.toggle("active",x===b));render()});
grid.addEventListener("click",e=>{const save=e.target.closest("[data-save]");if(save){toggleSaved(save.dataset.save);return}const details=e.target.closest("[data-detail]");if(details)openDetails(details.dataset.detail)});
document.querySelector("#dialog-content").addEventListener("click",e=>{const save=e.target.closest("[data-save]");if(save)toggleSaved(save.dataset.save)});
function toggleSaved(id){if(saved.has(id))saved.delete(id);else saved.add(id);localStorage.setItem("schemesaathi-saved",JSON.stringify([...saved]));render();if(dialog.open){const s=schemes.find(item=>item.id===id);openDetails(id)}}
search.addEventListener("input",render);
document.querySelector("#sort").addEventListener("change",render);
clearButton.addEventListener("click",clearFilters);
document.querySelector("#empty-clear").addEventListener("click",clearFilters);
document.querySelector("#dialog-close").addEventListener("click",()=>dialog.close());
dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
document.querySelector("#saved-shortcut").addEventListener("click",()=>{activeCategory="all";search.value="";document.querySelectorAll(".filter-chip").forEach(b=>b.classList.toggle("active",b.dataset.category==="all"));render();if(saved.size){grid.innerHTML=schemes.filter(s=>saved.has(s.id)).map(s=>'<article class="scheme-card"><div class="card-top"><span class="scheme-icon">'+s.icon+'</span><span class="category-label">'+s.categoryLabel+'</span><button class="save-button saved" data-save="'+s.id+'" aria-label="Remove saved scheme">♥</button></div><h3>'+s.name+'</h3><p>'+s.summary+'</p><div class="card-bottom"><span class="benefit">'+s.benefit+'</span><button class="learn-button" data-detail="'+s.id+'">Details <span>↗</span></button></div></article>').join("");document.querySelector("#results-label").textContent="Your saved schemes"}});
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();search.focus()}});
render();